In [6]:
import cv2
import numpy as np
from utils import plot_in_one_window,to_jpg
# args for plot_in_one_window should be at least 2 [], e.g.[[img]]

#### convert .png into .jpg

In [4]:
to_jpg('geometry.png')

#### load original image

In [26]:
img = cv2.imread('geometry.jpg')
h,w,c = img.shape
img = cv2.resize(img,(int(w/4),int(h/4)))
print(np.max(img))
cv2.imshow('geometry',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

255


#### gray and blur

In [8]:
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(imgGray.shape)
imgBlur = cv2.GaussianBlur(imgGray,ksize=(7,7),sigmaX=1)
print(imgBlur.shape)
# plot in one window, plots must have same shape
join_img = plot_in_one_window([[img,imgGray,imgBlur]])
cv2.imshow('ori gray blur',join_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(200, 198)
(200, 198)


#### edge detection

In [35]:
imgCanny = cv2.Canny(imgBlur,50,50)
join_img = plot_in_one_window([[img,imgGray,imgBlur],
                               [imgCanny,imgCanny,imgCanny]])
cv2.imshow('ori gray blur and contours',join_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### contours extraction

In [81]:
# extract the contours from the image.
# cv2.findContours() works best on binary images, so we should first apply thresholding techniques, Sobel edges, etc.
# args of cv2.findContours():
#   mode: contour retrieval mode
#   method: contour approximation method
contours,hierarchy = cv2.findContours(image=imgCanny,
                                      mode=cv2.RETR_EXTERNAL,
                                      method=cv2.CHAIN_APPROX_NONE)
print(f'what are contours: {type(contours)}')
print(f'Number of Contours found = {len(contours)}')
print(f'first Contour {len(contours[2])}')

# draw contours on copy of original image
imgContours = img.copy()
imgPoly = img.copy()
imgBound = img.copy()
for cnt in contours:
    print('===================================================')
    print(f'contour: {cnt}')
    # calculate the area of each contour
    area = cv2.contourArea(cnt)
    print(f'area: {area}')
    # only select some contours to draw
    if area > 800:
        # draw contours
        # args of cv2.drawContours():
        #   contours: contour to be drawn
        #   contourIdx: Parameter indicating a contour to draw. If it is negative, all the contours are drawn
        cv2.drawContours(image=imgContours,
                         contours=cnt,
                         contourIdx=-1,
                         color=(255,125,0),
                         thickness=1)
        # calculate perimeter
        # args of cv2.arcLength():
        #   curve: Input vector of 2D points
        #   closed: Flag indicating whether the curve is closed or not.
        peri = cv2.arcLength(curve=cnt,closed=True)
        print(f'perimeter: {peri}')
        # Approximates a polygonal curve(s) with the specified precision
        # args of cv2.approxPolyDP():
        #   curve: Input vector of 2D points
        #   epsilon: Parameter specifying the approximation accuracy. This is the maximum distance between the original curve and its approximation.
        #   closed: If true, the approximated curve is closed (its first and last vertices are connected). Otherwise, it is not closed.
        approx = cv2.approxPolyDP(curve=cnt,epsilon=0.02*peri,closed=True)
        print(f'corner points of approximated Polygon: {approx}')
        cv2.drawContours(image=imgPoly,
                         contours=approx,
                         contourIdx=-1,
                         color=(255,0,125),
                         thickness=5)
        # get parameters of bounding box:
        # The function calculates and returns the minimal up-right bounding rectangle for the specified point set or non-zero pixels of gray-scale image.
        # args of cv2.boundingRect:
        #   array: Input gray-scale image or 2D point set
        x,y,w,h = cv2.boundingRect(array=approx)
        # draw bounding box:
        # args of cv2.rectangle():
        #   pt1: Vertex of the rectangle
        #   pt2: Vertex of the rectangle opposite to pt1
        #   pt1: Vertex of the rectangle
        #   pt1: Vertex of the rectangle
        cv2.rectangle(img=imgBound,
                      pt1=(x,y),
                      pt2=(x+w,y+h),
                      color=(0,120,200),
                      thickness=2)
        # Annotate what shape it is
        # args of cv2.putText():
        #   org: the coordinates of the bottom-left corner of the text string in the image
        #   fontFace: font style
        what_shape = lambda num_corner: 'tri' if num_corner==3 else ('rec' if num_corner==4 else 'circle')
        cv2.putText(img=imgBound,
                    text=what_shape(len(approx)),
                    org=(int(x+w*0.25),int(y+h*0.5)),
                    fontFace=50,
                    fontScale=0.5,
                    color=(0,0,0),
                    thickness=1)

join_img = plot_in_one_window([[img,imgGray,imgCanny],
                               [imgContours,imgPoly,imgBound]])
cv2.imshow('ori gray canny contours polygon bounding_box',join_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

what are contours: <class 'tuple'>
Number of Contours found = 17
first Contour 139
contour: [[[ 54 162]]

 [[ 53 163]]

 [[ 52 163]]

 [[ 52 164]]

 [[ 51 165]]

 [[ 51 166]]

 [[ 51 167]]

 [[ 51 168]]

 [[ 51 169]]

 [[ 51 170]]

 [[ 51 171]]

 [[ 51 172]]

 [[ 51 173]]

 [[ 51 174]]

 [[ 51 175]]

 [[ 51 176]]

 [[ 51 177]]

 [[ 51 178]]

 [[ 51 179]]

 [[ 51 180]]

 [[ 51 181]]

 [[ 51 182]]

 [[ 51 183]]

 [[ 51 184]]

 [[ 52 185]]

 [[ 52 186]]

 [[ 53 186]]

 [[ 54 187]]

 [[ 55 187]]

 [[ 56 187]]

 [[ 57 187]]

 [[ 58 187]]

 [[ 59 187]]

 [[ 60 187]]

 [[ 61 187]]

 [[ 62 187]]

 [[ 63 187]]

 [[ 64 187]]

 [[ 65 187]]

 [[ 66 187]]

 [[ 67 187]]

 [[ 68 187]]

 [[ 69 187]]

 [[ 70 187]]

 [[ 71 187]]

 [[ 72 187]]

 [[ 73 187]]

 [[ 74 187]]

 [[ 75 187]]

 [[ 76 187]]

 [[ 77 187]]

 [[ 78 187]]

 [[ 79 187]]

 [[ 80 187]]

 [[ 81 187]]

 [[ 82 187]]

 [[ 83 187]]

 [[ 84 187]]

 [[ 85 187]]

 [[ 86 187]]

 [[ 87 187]]

 [[ 88 187]]

 [[ 89 187]]

 [[ 90 187]]

 [[ 91 187]]